-- Migration: Create symbols table
-- Date: 2025-01-XX
-- Description: Add comprehensive symbols table for NASDAQ stocks

CREATE TABLE IF NOT EXISTS symbols (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    sector TEXT,
    market_cap TEXT,
    exchange TEXT DEFAULT 'NASDAQ',
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_symbols_symbol ON symbols(symbol);
CREATE INDEX IF NOT EXISTS idx_symbols_sector ON symbols(sector);
CREATE INDEX IF NOT EXISTS idx_symbols_market_cap ON symbols(market_cap);
CREATE INDEX IF NOT EXISTS idx_symbols_exchange ON symbols(exchange);
CREATE INDEX IF NOT EXISTS idx_symbols_active ON symbols(is_active);

-- Insert initial NASDAQ symbols data
INSERT OR IGNORE INTO symbols (symbol, name, sector, market_cap) VALUES
-- Major ETFs
('QQQ', 'Invesco QQQ Trust', 'ETF', 'ETF'),
('TQQQ', 'ProShares UltraPro QQQ', 'ETF', 'ETF'),
('SQQQ', 'ProShares UltraPro Short QQQ', 'ETF', 'ETF'),
('SPY', 'SPDR S&P 500 ETF Trust', 'ETF', 'ETF'),
('VTI', 'Vanguard Total Stock Market ETF', 'ETF', 'ETF'),
('VOO', 'Vanguard S&P 500 ETF', 'ETF', 'ETF'),
('ARKK', 'ARK Innovation ETF', 'ETF', 'ETF'),
('IWM', 'iShares Russell 2000 ETF', 'ETF', 'ETF'),

-- Major Tech Companies (Top 30 by Market Cap)
('NVDA', 'NVIDIA Corporation', 'Technology', 'Large Cap'),
('MSFT', 'Microsoft Corporation', 'Technology', 'Large Cap'),
('AAPL', 'Apple Inc.', 'Technology', 'Large Cap'),
('GOOG', 'Alphabet Inc. (Class C)', 'Technology', 'Large Cap'),
('GOOGL', 'Alphabet Inc. (Class A)', 'Technology', 'Large Cap'),
('AMZN', 'Amazon.com Inc.', 'Consumer Discretionary', 'Large Cap'),
('META', 'Meta Platforms Inc.', 'Technology', 'Large Cap'),
('AVGO', 'Broadcom Inc.', 'Technology', 'Large Cap'),
('TSLA', 'Tesla Inc.', 'Consumer Discretionary', 'Large Cap'),
('NFLX', 'Netflix Inc.', 'Communication Services', 'Large Cap'),
('COST', 'Costco Wholesale Corporation', 'Consumer Staples', 'Large Cap'),
('PLTR', 'Palantir Technologies Inc.', 'Technology', 'Large Cap'),
('ASML', 'ASML Holding N.V.', 'Technology', 'Large Cap'),
('AMD', 'Advanced Micro Devices Inc.', 'Technology', 'Large Cap'),
('TMUS', 'T-Mobile US Inc.', 'Communication Services', 'Large Cap'),
('CSCO', 'Cisco Systems Inc.', 'Technology', 'Large Cap'),
('AZN', 'AstraZeneca PLC', 'Healthcare', 'Large Cap'),
('LIN', 'Linde plc', 'Materials', 'Large Cap'),
('PEP', 'PepsiCo Inc.', 'Consumer Staples', 'Large Cap'),
('INTU', 'Intuit Inc.', 'Technology', 'Large Cap'),
('SHOP', 'Shopify Inc.', 'Technology', 'Large Cap'),
('TXN', 'Texas Instruments Incorporated', 'Technology', 'Large Cap'),
('BKNG', 'Booking Holdings Inc.', 'Consumer Discretionary', 'Large Cap'),
('ISRG', 'Intuitive Surgical Inc.', 'Healthcare', 'Large Cap'),
('QCOM', 'QUALCOMM Incorporated', 'Technology', 'Large Cap'),
('PDD', 'PDD Holdings Inc.', 'Consumer Discretionary', 'Large Cap'),
('AMGN', 'Amgen Inc.', 'Healthcare', 'Large Cap'),
('ADBE', 'Adobe Inc.', 'Technology', 'Large Cap'),
('APP', 'AppLovin Corporation', 'Technology', 'Large Cap'),
('ARM', 'Arm Holdings plc', 'Technology', 'Large Cap'),
('GILD', 'Gilead Sciences Inc.', 'Healthcare', 'Large Cap'),
('HON', 'Honeywell International Inc.', 'Industrials', 'Large Cap'),
('MU', 'Micron Technology Inc.', 'Technology', 'Large Cap'),

-- Additional Major Companies
('ADP', 'Automatic Data Processing Inc.', 'Technology', 'Large Cap'),
('REGN', 'Regeneron Pharmaceuticals Inc.', 'Healthcare', 'Large Cap'),
('CME', 'CME Group Inc.', 'Financial Services', 'Large Cap'),
('KLAC', 'KLA Corporation', 'Technology', 'Large Cap'),
('SNPS', 'Synopsys Inc.', 'Technology', 'Large Cap'),
('CDNS', 'Cadence Design Systems Inc.', 'Technology', 'Large Cap'),
('ORLY', 'O\'Reilly Automotive Inc.', 'Consumer Discretionary', 'Large Cap'),
('MNST', 'Monster Beverage Corporation', 'Consumer Staples', 'Large Cap'),
('PAYX', 'Paychex Inc.', 'Technology', 'Large Cap'),
('MAR', 'Marriott International Inc.', 'Consumer Discretionary', 'Large Cap'),
('CTAS', 'Cintas Corporation', 'Industrials', 'Large Cap'),
('WDAY', 'Workday Inc.', 'Technology', 'Large Cap'),
('CPRT', 'Copart Inc.', 'Industrials', 'Large Cap'),
('ODFL', 'Old Dominion Freight Line Inc.', 'Industrials', 'Large Cap'),
('FAST', 'Fastenal Company', 'Industrials', 'Large Cap'),
('IDXX', 'IDEXX Laboratories Inc.', 'Healthcare', 'Large Cap'),
('BIIB', 'Biogen Inc.', 'Healthcare', 'Large Cap'),
('VRTX', 'Vertex Pharmaceuticals Inc.', 'Healthcare', 'Large Cap'),
('ILMN', 'Illumina Inc.', 'Healthcare', 'Large Cap'),
('DXCM', 'DexCom Inc.', 'Healthcare', 'Large Cap'),
('ALGN', 'Align Technology Inc.', 'Healthcare', 'Large Cap'),
('MTCH', 'Match Group Inc.', 'Communication Services', 'Large Cap'),
('ZM', 'Zoom Video Communications Inc.', 'Technology', 'Large Cap'),
('TEAM', 'Atlassian Corporation', 'Technology', 'Large Cap'),
('OKTA', 'Okta Inc.', 'Technology', 'Large Cap'),
('CRWD', 'CrowdStrike Holdings Inc.', 'Technology', 'Large Cap'),
('NET', 'Cloudflare Inc.', 'Technology', 'Large Cap'),
('DDOG', 'Datadog Inc.', 'Technology', 'Large Cap'),
('MDB', 'MongoDB Inc.', 'Technology', 'Large Cap'),
('TWLO', 'Twilio Inc.', 'Technology', 'Large Cap'),
('ROKU', 'Roku Inc.', 'Communication Services', 'Large Cap'),
('SNAP', 'Snap Inc.', 'Communication Services', 'Large Cap'),
('PINS', 'Pinterest Inc.', 'Communication Services', 'Large Cap'),

-- Gaming & E-commerce
('SE', 'Sea Limited', 'Consumer Discretionary', 'Large Cap'),
('GME', 'GameStop Corp.', 'Consumer Discretionary', 'Mid Cap'),
('HOOD', 'Robinhood Markets', 'Financial Services', 'Mid Cap'),
('EA', 'Electronic Arts Inc.', 'Communication Services', 'Large Cap'),
('ATVI', 'Activision Blizzard Inc.', 'Communication Services', 'Large Cap'),
('TTWO', 'Take-Two Interactive Software Inc.', 'Communication Services', 'Large Cap'),
('ZNGA', 'Zynga Inc.', 'Communication Services', 'Mid Cap'),

-- Electric Vehicles & Clean Energy
('NIO', 'NIO Inc.', 'Consumer Discretionary', 'Mid Cap'),
('XPEV', 'XPeng Inc.', 'Consumer Discretionary', 'Mid Cap'),
('LI', 'Li Auto Inc.', 'Consumer Discretionary', 'Mid Cap'),
('ENPH', 'Enphase Energy Inc.', 'Technology', 'Mid Cap'),
('SEDG', 'SolarEdge Technologies Inc.', 'Technology', 'Mid Cap'),
('RUN', 'Sunrun Inc.', 'Technology', 'Mid Cap'),
('PLUG', 'Plug Power Inc.', 'Industrials', 'Mid Cap'),
('FCEL', 'FuelCell Energy Inc.', 'Industrials', 'Small Cap'),

-- Cybersecurity
('ZS', 'Zscaler Inc.', 'Technology', 'Mid Cap'),
('FTNT', 'Fortinet Inc.', 'Technology', 'Large Cap'),
('PANW', 'Palo Alto Networks Inc.', 'Technology', 'Large Cap'),
('CHKP', 'Check Point Software Technologies Ltd.', 'Technology', 'Large Cap'),
('CYBR', 'CyberArk Software Ltd.', 'Technology', 'Mid Cap'),
('SAIL', 'SailPoint Technologies Holdings Inc.', 'Technology', 'Mid Cap'),

-- AI & Machine Learning
('AI', 'C3.ai Inc.', 'Technology', 'Mid Cap'),
('PATH', 'UiPath Inc.', 'Technology', 'Mid Cap'),
('RDFN', 'Redfin Corporation', 'Real Estate', 'Mid Cap'),
('Z', 'Zillow Group Inc.', 'Real Estate', 'Mid Cap'),
('OPEN', 'Opendoor Technologies Inc.', 'Real Estate', 'Mid Cap'),

-- Financial Services
('COIN', 'Coinbase Global Inc.', 'Financial Services', 'Large Cap'),
('SQ', 'Block Inc.', 'Financial Services', 'Large Cap'),
('V', 'Visa Inc.', 'Financial Services', 'Large Cap'),
('MA', 'Mastercard Incorporated', 'Financial Services', 'Large Cap'),
('AXP', 'American Express Company', 'Financial Services', 'Large Cap'),
('JPM', 'JPMorgan Chase & Co.', 'Financial Services', 'Large Cap'),
('BAC', 'Bank of America Corporation', 'Financial Services', 'Large Cap'),
('WFC', 'Wells Fargo & Company', 'Financial Services', 'Large Cap'),
('GS', 'Goldman Sachs Group Inc.', 'Financial Services', 'Large Cap'),
('MS', 'Morgan Stanley', 'Financial Services', 'Large Cap'),

-- Healthcare & Biotech
('JNJ', 'Johnson & Johnson', 'Healthcare', 'Large Cap'),
('PFE', 'Pfizer Inc.', 'Healthcare', 'Large Cap'),
('UNH', 'UnitedHealth Group Incorporated', 'Healthcare', 'Large Cap'),
('ABBV', 'AbbVie Inc.', 'Healthcare', 'Large Cap'),
('TMO', 'Thermo Fisher Scientific Inc.', 'Healthcare', 'Large Cap'),
('DHR', 'Danaher Corporation', 'Healthcare', 'Large Cap'),
('BMY', 'Bristol-Myers Squibb Company', 'Healthcare', 'Large Cap'),
('ABT', 'Abbott Laboratories', 'Healthcare', 'Large Cap'),
('LLY', 'Eli Lilly and Company', 'Healthcare', 'Large Cap'),
('NVO', 'Novo Nordisk A/S', 'Healthcare', 'Large Cap'),

-- Consumer & Retail
('WMT', 'Walmart Inc.', 'Consumer Staples', 'Large Cap'),
('HD', 'The Home Depot Inc.', 'Consumer Discretionary', 'Large Cap'),
('MCD', 'McDonald\'s Corporation', 'Consumer Discretionary', 'Large Cap'),
('SBUX', 'Starbucks Corporation', 'Consumer Discretionary', 'Large Cap'),
('NKE', 'NIKE Inc.', 'Consumer Discretionary', 'Large Cap'),
('LULU', 'Lululemon Athletica Inc.', 'Consumer Discretionary', 'Large Cap'),
('ULTA', 'Ulta Beauty Inc.', 'Consumer Discretionary', 'Mid Cap'),
('TGT', 'Target Corporation', 'Consumer Discretionary', 'Large Cap'),
('F', 'Ford Motor Company', 'Consumer Discretionary', 'Large Cap'),
('GM', 'General Motors Company', 'Consumer Discretionary', 'Large Cap'),
('STLA', 'Stellantis N.V.', 'Consumer Discretionary', 'Large Cap'),
('TM', 'Toyota Motor Corporation', 'Consumer Discretionary', 'Large Cap'),
('HMC', 'Honda Motor Co. Ltd.', 'Consumer Discretionary', 'Large Cap'),
('BMWYY', 'BMW AG', 'Consumer Discretionary', 'Large Cap'),
('MBGYY', 'Mercedes-Benz Group AG', 'Consumer Discretionary', 'Large Cap'),
('VWAGY', 'Volkswagen AG', 'Consumer Discretionary', 'Large Cap'),

-- Industrial & Manufacturing
('CAT', 'Caterpillar Inc.', 'Industrials', 'Large Cap'),
('DE', 'Deere & Company', 'Industrials', 'Large Cap'),
('BA', 'Boeing Company', 'Industrials', 'Large Cap'),
('GE', 'General Electric Company', 'Industrials', 'Large Cap'),
('MMM', '3M Company', 'Industrials', 'Large Cap'),
('UPS', 'United Parcel Service Inc.', 'Industrials', 'Large Cap'),
('FDX', 'FedEx Corporation', 'Industrials', 'Large Cap'),
('RTX', 'Raytheon Technologies Corporation', 'Industrials', 'Large Cap'),
('LMT', 'Lockheed Martin Corporation', 'Industrials', 'Large Cap'),
('NOC', 'Northrop Grumman Corporation', 'Industrials', 'Large Cap'),
('GD', 'General Dynamics Corporation', 'Industrials', 'Large Cap'),
('EMR', 'Emerson Electric Co.', 'Industrials', 'Large Cap'),
('ETN', 'Eaton Corporation plc', 'Industrials', 'Large Cap'),
('ITW', 'Illinois Tool Works Inc.', 'Industrials', 'Large Cap'),
('PH', 'Parker-Hannifin Corporation', 'Industrials', 'Large Cap'),
('ROK', 'Rockwell Automation Inc.', 'Industrials', 'Large Cap'),
('XYL', 'Xylem Inc.', 'Industrials', 'Mid Cap'),
('DOV', 'Dover Corporation', 'Industrials', 'Large Cap'),
('AME', 'AMETEK Inc.', 'Industrials', 'Large Cap'),
('FTV', 'Fortive Corporation', 'Industrials', 'Large Cap'),
('IEX', 'IDEX Corporation', 'Industrials', 'Mid Cap'),
('GWW', 'W.W. Grainger Inc.', 'Industrials', 'Large Cap'),
('WAB', 'Wabtec Corporation', 'Industrials', 'Mid Cap'),
('PWR', 'Quanta Services Inc.', 'Industrials', 'Mid Cap'),
('J', 'Jacobs Engineering Group Inc.', 'Industrials', 'Mid Cap'),
('ACM', 'AECOM', 'Industrials', 'Mid Cap'),
('FLR', 'Fluor Corporation', 'Industrials', 'Mid Cap'),
('KBR', 'KBR Inc.', 'Industrials', 'Mid Cap'),
('EME', 'EMCOR Group Inc.', 'Industrials', 'Mid Cap'),
('TXT', 'Textron Inc.', 'Industrials', 'Mid Cap'),
('LHX', 'L3Harris Technologies Inc.', 'Industrials', 'Large Cap'),
('TDG', 'TransDigm Group Incorporated', 'Industrials', 'Large Cap'),
('HEI', 'HEICO Corporation', 'Industrials', 'Mid Cap'),
('WCC', 'WESCO International Inc.', 'Industrials', 'Mid Cap'),
('GPC', 'Genuine Parts Company', 'Consumer Discretionary', 'Large Cap'),
('ORLY', 'O\'Reilly Automotive Inc.', 'Consumer Discretionary', 'Large Cap'),
('AZO', 'AutoZone Inc.', 'Consumer Discretionary', 'Large Cap'),
('AAP', 'Advance Auto Parts Inc.', 'Consumer Discretionary', 'Mid Cap'),
('LKQ', 'LKQ Corporation', 'Consumer Discretionary', 'Mid Cap'),
('KMX', 'CarMax Inc.', 'Consumer Discretionary', 'Mid Cap'),
('CARG', 'CarGurus Inc.', 'Communication Services', 'Small Cap'),
('CVNA', 'Carvana Co.', 'Consumer Discretionary', 'Mid Cap'),
('AN', 'AutoNation Inc.', 'Consumer Discretionary', 'Mid Cap'),
('PAG', 'Penske Automotive Group Inc.', 'Consumer Discretionary', 'Mid Cap'),
('LAD', 'Lithia Motors Inc.', 'Consumer Discretionary', 'Mid Cap'),
('SAH', 'Sonic Automotive Inc.', 'Consumer Discretionary', 'Small Cap'),
('ABG', 'Asbury Automotive Group Inc.', 'Consumer Discretionary', 'Mid Cap'),
('GPI', 'Group 1 Automotive Inc.', 'Consumer Discretionary', 'Mid Cap'),
('HOG', 'Harley-Davidson Inc.', 'Consumer Discretionary', 'Mid Cap'),
('PII', 'Polaris Inc.', 'Consumer Discretionary', 'Mid Cap'),
('THO', 'Thor Industries Inc.', 'Consumer Discretionary', 'Mid Cap'),
('WGO', 'Winnebago Industries Inc.', 'Consumer Discretionary', 'Mid Cap'),
('LCII', 'LCI Industries Inc.', 'Consumer Discretionary', 'Small Cap'),
('REVG', 'REV Group Inc.', 'Industrials', 'Small Cap'),
('OSK', 'Oshkosh Corporation', 'Industrials', 'Mid Cap'),
('ALV', 'Autoliv Inc.', 'Consumer Discretionary', 'Mid Cap'),
('BWA', 'BorgWarner Inc.', 'Consumer Discretionary', 'Mid Cap'),
('LEA', 'Lear Corporation', 'Consumer Discretionary', 'Mid Cap'),
('VNE', 'Veoneer Inc.', 'Consumer Discretionary', 'Small Cap'),
('APTV', 'Aptiv PLC', 'Consumer Discretionary', 'Large Cap'),

-- Real Estate
('DLR', 'Digital Realty Trust Inc.', 'Real Estate', 'Large Cap'),
('WELL', 'Welltower Inc.', 'Real Estate', 'Large Cap'),
('VICI', 'VICI Properties Inc.', 'Real Estate', 'Large Cap'),
('PSA', 'Public Storage', 'Real Estate', 'Large Cap'),
('EQR', 'Equity Residential', 'Real Estate', 'Large Cap'),
('AVB', 'AvalonBay Communities Inc.', 'Real Estate', 'Large Cap'),
('MAA', 'Mid-America Apartment Communities Inc.', 'Real Estate', 'Large Cap'),
('ESS', 'Essex Property Trust Inc.', 'Real Estate', 'Large Cap'),
('UDR', 'UDR Inc.', 'Real Estate', 'Mid Cap'),
('CPT', 'Camden Property Trust', 'Real Estate', 'Mid Cap'),
('BXP', 'Boston Properties Inc.', 'Real Estate', 'Large Cap'),
('SLG', 'SL Green Realty Corp.', 'Real Estate', 'Mid Cap'),
('VNO', 'Vornado Realty Trust', 'Real Estate', 'Mid Cap'),
('SPG', 'Simon Property Group Inc.', 'Real Estate', 'Large Cap'),
('MAC', 'Macerich Company', 'Real Estate', 'Small Cap'),
('TCO', 'Taubman Centers Inc.', 'Real Estate', 'Small Cap'),
('KIM', 'Kimco Realty Corporation', 'Real Estate', 'Mid Cap'),
('REG', 'Regency Centers Corporation', 'Real Estate', 'Mid Cap'),
('FRT', 'Federal Realty Investment Trust', 'Real Estate', 'Mid Cap'),
('O', 'Realty Income Corporation', 'Real Estate', 'Large Cap'),
('NNN', 'National Retail Properties Inc.', 'Real Estate', 'Mid Cap'),
('ADC', 'Agree Realty Corporation', 'Real Estate', 'Mid Cap'),
('STOR', 'STORE Capital Corporation', 'Real Estate', 'Mid Cap'),
('WPC', 'W.P. Carey Inc.', 'Real Estate', 'Large Cap'),
('EPR', 'EPR Properties', 'Real Estate', 'Mid Cap'),
('GLPI', 'Gaming and Leisure Properties Inc.', 'Real Estate', 'Mid Cap'),
('VTR', 'Ventas Inc.', 'Real Estate', 'Mid Cap'),
('HCP', 'HCP Inc.', 'Real Estate', 'Mid Cap'),
('HR', 'Healthcare Realty Trust Incorporated', 'Real Estate', 'Mid Cap'),
('PEAK', 'Healthpeak Properties Inc.', 'Real Estate', 'Mid Cap'),
('DOC', 'Physicians Realty Trust', 'Real Estate', 'Small Cap'),
('GMRE', 'Global Medical REIT Inc.', 'Real Estate', 'Small Cap'),
('LTC', 'LTC Properties Inc.', 'Real Estate', 'Small Cap'),
('SBRA', 'Sabra Health Care REIT Inc.', 'Real Estate', 'Small Cap'),
('OHI', 'Omega Healthcare Investors Inc.', 'Real Estate', 'Mid Cap'),
('MPW', 'Medical Properties Trust Inc.', 'Real Estate', 'Mid Cap'),
('CTRE', 'CareTrust REIT Inc.', 'Real Estate', 'Small Cap'),
('NHI', 'National Health Investors Inc.', 'Real Estate', 'Small Cap'),
('UHT', 'Universal Health Realty Income Trust', 'Real Estate', 'Small Cap'),
('HTA', 'Healthcare Trust of America Inc.', 'Real Estate', 'Mid Cap');

-- Update timestamp
UPDATE symbols SET updated_at = CURRENT_TIMESTAMP;
